Add `addToQueue` extension to mediaplayer entity
YIO-Remote/remote-software pull request #497
Opened 2020-08-11 14:20 UTC by jadlers

This PR will add an `addToQueue` extension to the `MediaPlayer` entity.

There seems to be some work already done preparing for the feature of queuing songs. This PR is needed in order for my "add to queue" implementation for the Spotify integration to work. See that PR here: 

Is this the way it was intended to be used? It's my first contribution and would be glad for any feedback!

2020-08-11 16:46 UTC, zehnm commented on sources/entities/mediaplayer.cpp
> +    command(MediaPlayerDef::C_QUEUE, map);
Same issue as with the spotify integration: MediaPlayerDef is part of the shared integrations.library project, which also requires a PR before new enums can be used in remote-software and the integrations ;-)
```
../sources/entities/mediaplayer.cpp:153:29: error: 'C_QUEUE' is not a member of 'MediaPlayerDef'
     command(MediaPlayerDef::C_QUEUE, map);
                             ^~~~~~~
```

2020-08-12 14:37 UTC, jadlers commented
When I started implementing the feature I came across these lines https://github.com/YIO-Remote/remote-software/blob/master/basic_ui/ContextMenu.qml#L122-L123. All I did in this PR is to implement the function called. I'm guessing something was planned for queuing since these lines  where added 8 months ago by @martonborzak.

2020-08-13 20:48 UTC, martonborzak approved these changes

2020-08-13 21:42 UTC, zehnm requested changes

2020-08-13 21:42 UTC, zehnm commented on sources/entities/mediaplayer.cpp
> +    command(MediaPlayerDef::C_QUEUE, map);
The required PR of integrations.library is merged and a new release v0.5.1 has been created.
Required change for this PR: modify dependencies.cfg to include the new release
```
integrations.library: v0.5.1
```

2020-08-17 11:51 UTC, jadlers commented
Updated here as well, thanks again!

2020-08-17 20:42 UTC, zehnm approved these changes

2020-08-17 20:44 UTC, merged